 const changeDataArray = [
    {
      ref: 'mailRef',
      type: 'mail',
      name: 'email',
      placeholder: 'pochta@yandex.ru',
      label: 'Почта',
      errorClass: 'profile-error',
      labelClass: 'profile-key',
      ControlledInputClass: 'profile-info-flex-block',
    },
    {
      ref: 'loginInputRef',
      type: 'login',
      name: 'login',
      placeholder: 'ivanivanov',
      label: 'Логин',
      errorClass: 'profile-error',
      labelClass: 'profile-key',
      ControlledInputClass: 'profile-info-flex-block',
    },
    {
      ref: 'firstNameRef',
      name: 'first_name',
      placeholder: 'Иван',
      type: 'first_name',
      label: 'Имя',
      errorClass: 'profile-error',
      labelClass: 'profile-key',
      ControlledInputClass: 'profile-info-flex-block',
    },
    {
      ref: 'lastNameRef',
      name: 'second_name',
      placeholder: 'Иванов',
      type: 'last_name',
      label: 'Фамилия',
      errorClass: 'profile-error',
      labelClass: 'profile-key',
      ControlledInputClass: 'profile-info-flex-block',
    },
    {
      ref: 'firstNameInChatRef',
      name: 'display_name',
      placeholder: 'Иван',
      type: 'last_name',
      label: 'Имя в чате',
      errorClass: 'profile-error',
      labelClass: 'profile-key',
      ControlledInputClass: 'profile-info-flex-block',
    },
    {
      ref: 'phoneRef',
      name: 'phone',
      placeholder: '+7(909)9673030',
      type: 'phone',
      label: 'Телефон',
      errorClass: 'profile-error',
      labelClass: 'profile-key',
      ControlledInputClass: 'profile-info-flex-block',
    },
  ]

  export default changeDataArray;