export const dialogues = [
    {
      nickName: 'Андрей',
      time: '12:12',
      messageText: 'messageText1',
      messageNotification: 2,
      avatar: 'https://cdn-icons-png.flaticon.com/512/924/924915.png',
    },
    {
      nickName: 'Витя',
      time: '16:09',
      messageText: 'messageText2',
      messageNotification: 0,
      avatar: 'https://cdn-icons-png.flaticon.com/512/7921/7921042.png',
    },
    {
      nickName: 'Лола',
      time: '06:16',
      messageText: 'messageText3',
      messageNotification: 2,
      avatar: 'https://cdn-icons-png.flaticon.com/512/6743/6743079.png',
    },
    {
      nickName: 'Андрей2',
      time: '12:12',
      messageText: 'messageText4',
      messageNotification: 0,
      avatar: 'https://cdn-icons-png.flaticon.com/512/924/924915.png',
    },
    {
      nickName: 'Вова',
      time: '12:12',
      messageText: 'messageText1',
      messageNotification: 1,
      avatar: 'https://cdn-icons-png.flaticon.com/512/924/924915.png',
    },
    {
      nickName: 'Витя3',
      time: '16:09',
      messageText: 'messageText2',
      messageNotification: 1,
      avatar: 'https://cdn-icons-png.flaticon.com/512/7921/7921042.png',
    },
    {
      nickName: 'Лола123',
      time: '06:16',
      messageText: 'messageText3',
      messageNotification: 2,
      avatar: 'https://cdn-icons-png.flaticon.com/512/6743/6743079.png',
    },
    {
      nickName: 'Андрей2',
      time: '12:12',
      messageText: 'messageText4',
      messageNotification: 0,
      avatar: 'https://cdn-icons-png.flaticon.com/512/924/924915.png',
    },
    {
      nickName: 'Андрей2',
      time: '12:12',
      messageText: 'messageText4',
      messageNotification: 2,
      avatar: 'https://cdn-icons-png.flaticon.com/512/924/924915.png',
    },
    {
      nickName: 'Андрей',
      time: '12:12',
      messageText: 'messageText1',
      messageNotification: 2,
      avatar: 'https://cdn-icons-png.flaticon.com/512/924/924915.png',
    },
    {
      nickName: 'Витя',
      time: '16:09',
      messageText: 'messageText2',
      messageNotification: 0,
      avatar: 'https://cdn-icons-png.flaticon.com/512/7921/7921042.png',
    },
    {
      nickName: 'Лола',
      time: '06:16',
      messageText: 'messageText3',
      messageNotification: 2,
      avatar: 'https://cdn-icons-png.flaticon.com/512/6743/6743079.png',
    },
    {
      nickName: 'Андрей2',
      time: '12:12',
      messageText: 'messageText4',
      messageNotification: 2,
      avatar: 'https://cdn-icons-png.flaticon.com/512/924/924915.png',
    },
  ];